# Google Cloud Build configuration for Cloud Run deployment
steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/hiker-bot:$SHORT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/hiker-bot:latest'
      - '.'
    id: 'build-image'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/hiker-bot:$SHORT_SHA'
    id: 'push-image-sha'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/hiker-bot:latest'
    id: 'push-image-latest'

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'hiker-bot'
      - '--image'
      - 'gcr.io/$PROJECT_ID/hiker-bot:$SHORT_SHA'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--timeout'
      - '300'
      - '--set-env-vars'
      - 'WHATSAPP_PHONE_NUMBER_ID=${_WHATSAPP_PHONE_NUMBER_ID},WHATSAPP_ACCESS_TOKEN=${_WHATSAPP_ACCESS_TOKEN},WEBHOOK_VERIFY_TOKEN=${_WEBHOOK_VERIFY_TOKEN},MONGODB_URI=${_MONGODB_URI},MONGODB_DB_NAME=${_MONGODB_DB_NAME},FLASK_DEBUG=false'
    id: 'deploy-cloud-run'

# Images to be pushed to the registry
images:
  - 'gcr.io/$PROJECT_ID/hiker-bot:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/hiker-bot:latest'

# Substitution variables (set these in Cloud Build triggers or via command line)
substitutions:
  _REGION: 'us-central1'
  _WHATSAPP_PHONE_NUMBER_ID: ''
  _WHATSAPP_ACCESS_TOKEN: ''
  _WEBHOOK_VERIFY_TOKEN: ''
  _MONGODB_URI: ''
  _MONGODB_DB_NAME: 'hiker_db'

# Build options
options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

timeout: '1200s'

